language: go
go:
    - 1.7
sudo: required
services:
    - docker
before_install:
    - sudo apt-get -y install texlive-xetex texlive-fonts-recommended texlive-latex-base texlive-latex-extra pandoc
    - go get -u -v github.com/spf13/hugo
    - openssl aes-256-cbc -K $encrypted_97c4de2fd153_key -iv $encrypted_97c4de2fd153_iv -in id_rsa_travis.enc -out id_rsa_travis -d
    - chmod 600 id_rsa_travis
    - eval "$(ssh-agent -s)" && ssh-add id_rsa_travis
