dist: xenial
language: c
sudo: required
before_install:
    - sudo apt-get -q update
    - sudo apt-get -y install
        texlive-latex-base
        texlive-latex-extra
        texlive-fonts-recommended
        texlive-xetex
        pandoc
        nim
        hugo
    - openssl aes-256-cbc
        -K $encrypted_97c4de2fd153_key
        -iv $encrypted_97c4de2fd153_iv
        -in id_rsa_travis.enc
        -out id_rsa_travis -d
    - chmod 600 id_rsa_travis
    - eval "$(ssh-agent -s)" && ssh-add id_rsa_travis
script: make
