language: c
sudo: required
env:
    - BRANCH=master
before_install:
    - sudo apt-get -q update
    - sudo apt-get -y install
        texlive-latex-base
        texlive-latex-extra
        texlive-fonts-recommended
        texlive-xetex
        pandoc
    - wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
    - sudo dpkg -i hugo_0.17-64bit.deb
    - openssl aes-256-cbc
        -K $encrypted_97c4de2fd153_key
        -iv $encrypted_97c4de2fd153_iv
        -in id_rsa_travis.enc
        -out id_rsa_travis -d
    - chmod 600 id_rsa_travis
    - eval "$(ssh-agent -s)" && ssh-add id_rsa_travis
    - |
        git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
        cd nim-$BRANCH
        git clone -b $BRANCH --depth 1 git://github.com/nim-lang/csources csources/
        cd csources
        sh build.sh
        cd ..
        rm -rf csources
        bin/nim c koch
        ./koch boot -d:release
        cd ..
before_script:
    - export PATH="nim-$BRANCH/bin${PATH:+:$PATH}"
script: make
